server:
  port: 8026
  session:
    timeout: 600

logging:
  path: logs/
  level:
    root: INFO

spring:
  profiles.active: mysql,dev,mongodb
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      jadira.usertype.autoRegisterUserTypes: true
    hibernate:
      naming-strategy: cn.tendata.crm.data.jpa.config.CustomNamingStrategy
      ddl-auto: update
  thymeleaf:
      enabled: true
      cache: false
      mode: LEGACYHTML5


security:
  ignored: /favicon.ico,css/**,/js/**,/fonts/**,/img/**,/webjars/**,/admin/app/**,/admin/assets/**,/admin/css/**,/admin/html/**,/admin/images/**

---
spring:
  profiles: mysql
  datasource:
    driver-class-name: ${datasource.driver-class-name:com.mysql.jdbc.Driver}
    url: ${datasource.url:jdbc:mysql://localhost:3306/tendata_crm}
    username: ${datasource.username:root}
    password: ${datasource.password:}
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

---
spring:
  profiles: mongodb
  data:
    mongodb:
          uri: mongodb://localhost/test



